set(sources
    src/event.cpp
    src/message_box.cpp
    src/renderer.cpp
    src/surface.cpp
    src/texture.cpp 
    src/window.cpp
)

set(headers
    include/sdl2++/color.hpp
    include/sdl2++/enums.hpp
    include/sdl2++/event.hpp
    include/sdl2++/init.hpp
    include/sdl2++/message_box.hpp
    include/sdl2++/pixel.hpp
    include/sdl2++/renderer.hpp
    include/sdl2++/shapes.hpp
    include/sdl2++/surface.hpp
    include/sdl2++/texture.hpp
    include/sdl2++/util.hpp
    include/sdl2++/window.hpp
)
